### ISSUE TITLE
recovery time and drive time

### ISSUE THREAD

**Issue by AuspeXeu** [tijmenvangulik/ErgometerJS#11]
These properties also seem like they have some funky values unless I am totally off with counting in my head... this probably needs some further investigation. Just putting this here to keep track.

**Comment by tijmenvangulik** [comment]
The most important values are correct, because I needed them. I have not checked all the values, like stroke count or other values. There are also bugs in the driver software especially the blue tooth. Devices can be on different firmwares. So I just use a subset of the values. A lot of values are derived values which you can also calculate in your own code. (this can safe bugs and performance because you need less calls)  If you find more bugs let me know.

Tijmen
