### ISSUE TITLE
setProgram

### ISSUE THREAD

**Issue by AuspeXeu** [tijmenvangulik/ErgometerJS#14]
I am trying to use the following code to select the first pre-programmed workout.

```
this.performanceMonitor.newCsafeBuffer()
          .setProgram({value: 1})
          .send()
```
It also correctly sends `f1 24 02 01 00 25 f2` to the PM5 and the `workoutDuration` value gets updated, however the screen on the PM5 does not change at all and if I start pulling it switches back to `Just row` any idea what I am missing?

**Comment by tijmenvangulik** [comment]
I found that the blue tooth csafe was very buggy. It is best to use the latest firmware. Some commands work others not. And this is not due to ergometerjs. Some times it starts working when I also put other commands in the same csafe buffer. I think it is best to contact concept2 with this case.

Tijmen

**Comment by tijmenvangulik** [comment]
Since you are now testing the setProgram. I assume you managed to fix the ble connection problem. How did you do that? I do not own blue tooth hardwere where I have the same connection problem so it is hard for me to fix this. So I am most  interested on info how to fix this..

Tijmen

**Comment by AuspeXeu** [comment]
So essentially I set this multiplex property true and serialized `startNotification`

**Comment by tijmenvangulik** [comment]
Thank you for the info, Good work!. I never needed the multiplex property because I did not own a blue tooth chip with these limitations (or maybe you connected to too many events to get into these trouble, it is best to limit the amount of events where you subscribe to ) . What did you exactly do, maybe it is something which I could implement as standard fix.

Tijmen

**Comment by AuspeXeu** [comment]
I'll create a pull request later today. I don't think there is a significant slow down while connecting to the PM5 so I guess it could be a general bluetooth fix.
