### ISSUE TITLE
Android Chrome events

### ISSUE THREAD

**Issue by n24005** [tijmenvangulik/ErgometerJS#16]
Hi,

Thanks for this work!   My code currently sets up handlers for RowingGeneralStatus and RowingAdditionalStatus1.  On my Windows 10 laptop, it works great.

However, on an Android running Chrome, using the same code, the RowingGeneralStatus handler fires as expected, but the RowingAdditionalStatus1 never fires.

Any thoughts?

Thanks,
Jeff

**Comment by tijmenvangulik** [comment]
Hi Jeff,

Ergometer-space also uses this event and it works on android. I think you have run into some android limitations. The amount of event where you can connect to is limited by:
- Your android version
- The hardware on your phone.

If you can not upgrade your phone you have the following possible work around:
- Limit the amount of events which you use
- Use csafe to get your data
- Set the multiplex property to true. (This will reduce the used events by duplexing the events)

Since I do not own hardware/software with these limitations it is hard for me to test this. I am interested in your  exact hardware/software setup and which of my proposed fixes worked for you..

Tijmen

**Comment by n24005** [comment]
Thanks very much for your reply.

It looks like setting multiplex to true fixed the issue.

The unit I am testing is a Samsung A10, Android version 10

Thanks again!
Jeff

**Comment by tijmenvangulik** [comment]
Thank you for your report,

I am thinking of building in an fix for this. It would be good to start with the multiplex option being switched of (you get the highest resolution of data) But when the driver sees that events are failing it will try to reconnect connect with the multiplex turned on. Since I do not own hardware which fails here I need some one to test if it really works. Can you help me with this?

Tijmen

**Comment by n24005** [comment]
Sure - I would be happy to
