### ISSUE TITLE
Questions regarding ErgometerJS application

### ISSUE THREAD

**Issue by mosesmc52** [tijmenvangulik/ErgometerJS#2]
Hi, 

I'm a little new to using Node.  Is it possible for me to use ErgometerJS within a node server that would receive REST requests and command multiple concept 2 Ergs? Where would I begin?

Also, are there any plans to get ErgometerJS to work with react-native?

Moses

**Comment by tijmenvangulik** [comment]
I have just checked. There is a react-native-ble driver. The documentation say’s that it is noble compatible. 

https://github.com/jacobrosenthal/react-native-ble <https://github.com/jacobrosenthal/react-native-ble>

ErgometerJS uses bleat which uses noble when it it can be found. To configure bleat to use noble check the bleat web site:

	https://github.com/thegecko/bleat

It should directly work. When it does not work and it can not be fixed with a simple patch, both bleat as ergometerJS have an adapter layer where you can make modified drivers.

Multiple ergometers using node is not difficult. I have done this my selves on my ergometer website:
	http://ergometer-space.org/ <http://ergometer-space.org/>
What you have to do is to find a node chat example which uses web sockets. Instead of sending text messages you will send data formatted in JSON. 

I would like to hear from you when you got react native working. If I need to do any modifications.

Tijmen 

P.S. additional advice, start directly using typescript. This saves a lot of time in the long run.

**Comment by mosesmc52** [comment]
Thanks!
